[build]
builder = "DOCKERFILE"
dockerfilePath = "trainer/Dockerfile"
watchPatterns = ["trainer/**", "classifier/**"]

[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
